/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Pantallas;

import Exepciones.PersistenciaException;
import dominio.Cliente;
import java.util.logging.Level;
import java.util.logging.Logger;
import Negocio.MenuPrincipal;

/**
 *Interfaz principal del programa donde se puede ir a otros menus y visualizar la tabla de cuentas
 * 
 * @author favel
 */
public class Menu_Principal extends javax.swing.JFrame {

    Cliente cliente;
    MenuPrincipal mp = new MenuPrincipal();
    
    /**
     * Creates new form Menu_Principal
     */
    public Menu_Principal(Cliente cliente) {
        initComponents();
        this.cliente = cliente;
        try {
            mp.llenarTabla(cliente, this.Tabla);
        } catch (PersistenciaException ex) {
            Logger.getLogger(Menu_Principal.class.getName()).log(Level.SEVERE, "No se lleno la tabla", ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BotonTransferencia = new javax.swing.JButton();
        BotonGenerarFolio = new javax.swing.JButton();
        BotonHistorial = new javax.swing.JButton();
        BotonAgregarSaldo = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        BotonAjustes = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BotonTransferencia.setBackground(new java.awt.Color(51, 153, 255));
        BotonTransferencia.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        BotonTransferencia.setForeground(new java.awt.Color(255, 255, 255));
        BotonTransferencia.setText("Trasnferencia");
        BotonTransferencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonTransferenciaActionPerformed(evt);
            }
        });

        BotonGenerarFolio.setBackground(new java.awt.Color(51, 153, 255));
        BotonGenerarFolio.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        BotonGenerarFolio.setForeground(new java.awt.Color(255, 255, 255));
        BotonGenerarFolio.setText("Generar Folio");
        BotonGenerarFolio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonGenerarFolioActionPerformed(evt);
            }
        });

        BotonHistorial.setBackground(new java.awt.Color(51, 153, 255));
        BotonHistorial.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        BotonHistorial.setForeground(new java.awt.Color(255, 255, 255));
        BotonHistorial.setText("Historial de movimientos");
        BotonHistorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonHistorialActionPerformed(evt);
            }
        });

        BotonAgregarSaldo.setBackground(new java.awt.Color(51, 153, 255));
        BotonAgregarSaldo.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        BotonAgregarSaldo.setForeground(new java.awt.Color(255, 255, 255));
        BotonAgregarSaldo.setText("Agregar Saldo");
        BotonAgregarSaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAgregarSaldoActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(51, 153, 255));

        jLabel9.setFont(new java.awt.Font("Arial Black", 3, 60)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Potro Banco");

        BotonAjustes.setBackground(new java.awt.Color(51, 153, 255));
        BotonAjustes.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        BotonAjustes.setForeground(new java.awt.Color(255, 255, 255));
        BotonAjustes.setText("---");
        BotonAjustes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAjustesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BotonAjustes, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BotonAjustes)
                .addGap(32, 32, 32))
        );

        Tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null}
            },
            new String [] {
                "Cuenta", "Saldo"
            }
        ));
        jScrollPane1.setViewportView(Tabla);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(BotonTransferencia, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BotonAgregarSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BotonGenerarFolio, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BotonHistorial))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(144, 144, 144))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonHistorial, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotonTransferencia, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotonAgregarSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotonGenerarFolio, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonTransferenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonTransferenciaActionPerformed
        dispose();
        new Menu_Transferencias(cliente).setVisible(true);
    }//GEN-LAST:event_BotonTransferenciaActionPerformed

    private void BotonGenerarFolioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonGenerarFolioActionPerformed
        dispose();
        new Menu_GenerarFolio(cliente).setVisible(true);
    }//GEN-LAST:event_BotonGenerarFolioActionPerformed

    private void BotonHistorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonHistorialActionPerformed
        dispose();
        new Menu_Historial(cliente).setVisible(true);
    }//GEN-LAST:event_BotonHistorialActionPerformed

    private void BotonAgregarSaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAgregarSaldoActionPerformed
        dispose();
        new Menu_AgregarSaldo(cliente).setVisible(true);
    }//GEN-LAST:event_BotonAgregarSaldoActionPerformed

    private void BotonAjustesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAjustesActionPerformed
        dispose();
        new Menu_Ajustes(cliente).setVisible(true);
    }//GEN-LAST:event_BotonAjustesActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonAgregarSaldo;
    private javax.swing.JButton BotonAjustes;
    private javax.swing.JButton BotonGenerarFolio;
    private javax.swing.JButton BotonHistorial;
    private javax.swing.JButton BotonTransferencia;
    private javax.swing.JTable Tabla;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
