/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Pantallas;

import ConexionBD.ConexionBD;
import dominio.Cliente;
import java.sql.Connection;
import java.util.logging.Logger;
import Negocio.Operaciones;

/**
 *
 * @author favel
 */
public class Menu_Historial extends javax.swing.JFrame {

    Cliente cliente;
    ConexionBD con = new ConexionBD();
    Operaciones op = new Operaciones();
    private static final Logger LOG = Logger.getLogger(Connection.class.getName());
    private boolean transferenciasFiltradas = false;
    private boolean retirosFiltrados = false;

    /**
     * Creates new form Menu_Historial
     */
    public Menu_Historial(Cliente cliente) {
        initComponents();
        this.cliente = cliente;
        op.llenarTablaHistorial(cliente, Tabla, "Todos");
    }

    private void filtrarOperacionesPorTipo(String tipoOperacion) {
        op.llenarTablaHistorial(cliente, Tabla, tipoOperacion);
        Tabla.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BotonRegresar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        BotonTransferencia = new javax.swing.JButton();
        BotonRetiros = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BotonRegresar.setBackground(new java.awt.Color(255, 0, 51));
        BotonRegresar.setForeground(new java.awt.Color(255, 255, 255));
        BotonRegresar.setText("<--");
        BotonRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonRegresarActionPerformed(evt);
            }
        });

        Tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Movimiento", "Cuenta", "Fecha", "Monto"
            }
        ));
        jScrollPane1.setViewportView(Tabla);

        jPanel1.setBackground(new java.awt.Color(51, 153, 255));

        jLabel9.setFont(new java.awt.Font("Arial Black", 3, 60)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Potro Banco");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                .addContainerGap())
        );

        BotonTransferencia.setBackground(new java.awt.Color(51, 153, 255));
        BotonTransferencia.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        BotonTransferencia.setForeground(new java.awt.Color(255, 255, 255));
        BotonTransferencia.setText("Filtrar Transferencias");
        BotonTransferencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonTransferenciaActionPerformed(evt);
            }
        });

        BotonRetiros.setBackground(new java.awt.Color(51, 153, 255));
        BotonRetiros.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        BotonRetiros.setForeground(new java.awt.Color(255, 255, 255));
        BotonRetiros.setText("Filtrar Retiros");
        BotonRetiros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonRetirosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(BotonRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(84, 84, 84)
                        .addComponent(BotonTransferencia, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(85, 85, 85)
                        .addComponent(BotonRetiros, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(136, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BotonRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BotonTransferencia, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BotonRetiros, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(41, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonRegresarActionPerformed
        dispose();
        new Menu_Principal(cliente).setVisible(true);
    }//GEN-LAST:event_BotonRegresarActionPerformed

    private void BotonTransferenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonTransferenciaActionPerformed
        if (transferenciasFiltradas) {
            op.llenarTablaHistorial(cliente, Tabla, "Todos");
            Tabla.repaint();
            BotonTransferencia.setText("Filtrar Transferencias");
            transferenciasFiltradas = false;
        } else {
            if (retirosFiltrados) {
                op.llenarTablaHistorial(cliente, Tabla, "Todos");
                Tabla.repaint();
                BotonRetiros.setText("Filtrar Retiros");
                retirosFiltrados = false;
            }
            filtrarOperacionesPorTipo("Transferencia");
            BotonTransferencia.setText("Restaurar");
            transferenciasFiltradas = true;
        }
    }//GEN-LAST:event_BotonTransferenciaActionPerformed

    private void BotonRetirosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonRetirosActionPerformed
        if (retirosFiltrados) {
            op.llenarTablaHistorial(cliente, Tabla, "Todos");
            Tabla.repaint();
            BotonRetiros.setText("Filtrar Retiros");
            retirosFiltrados = false;
        } else {
            if (transferenciasFiltradas) {
                op.llenarTablaHistorial(cliente, Tabla, "Todos");
                Tabla.repaint();
                BotonTransferencia.setText("Filtrar Transferencias");
                transferenciasFiltradas = false;
            }
            filtrarOperacionesPorTipo("Retiro");
            BotonRetiros.setText("Restaurar");
            retirosFiltrados = true;
        }
    }//GEN-LAST:event_BotonRetirosActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonRegresar;
    private javax.swing.JButton BotonRetiros;
    private javax.swing.JButton BotonTransferencia;
    private javax.swing.JTable Tabla;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
